### ISSUE TITLE
error creating filter and alarm

### ISSUE THREAD

**Issue by shashipratap** [dwp/terraform-aws-metric-filter-alarm#14]
I am using below code snippet 
```
module "my_metric_filter_alarm" {
  source = "dwp/metric-filter-alarm/aws"
  version = "2.0.1"
  #log_group_name    = module.cloudtrail_aws_cloudwatch_log_group.cloud_watch_logs_group_arn
  log_group_name = "cloudtrail-cloudwatch-log-group"
  metric_namespace = "CISBenchmark"
  pattern = "{ ($.eventName = CreateCustomerGateway) || ($.eventName = DeleteCustomerGateway) || ($.eventName = AttachInternetGateway) || ($.eventName = CreateInternetGateway) || ($.eventName = DeleteInternetGateway) || ($.eventName = DetachInternetGateway) }"
  metric_filter_name = "changed_nw_gw"
  metric_value = "1"
  alarm_name = "MyAlarm"
#  alarm_action_arns = ["${aws_sns_topic.MyTopic.arn}"]
  period = "300"
  evaluation_periods = "1"
  threshold = "1"
  statistic = "Sum"
  comparison_operator = "GreaterThanOrEqualToThreshold"
}
```

but it fails with error 

 `Error: Error creating CloudTrail: InvalidCloudWatchLogsRoleArnException: You must specify a role ARN as well as a log group.`

I dont see any option to provide log group arn in the module , also i dont see any option to provide metric_name , when we create a metric filter , there is an option to provide the metric name

**Comment by jonmelia** [comment]
You need to be creating the log group resource as shown below as a separate resource eg

`resource "aws_cloudwatch_log_group" "terratest_log_group" {
  name = "TerratestLogGroup"
}

resource "aws_sns_topic" "terratest_topic" {
  name         = "TerratestTopic"
  display_name = "Terratest Topic"
}

module "terratest_metric_filter_alarm" {
  source = "../"

  log_group_name    = aws_cloudwatch_log_group.terratest_log_group.name
  metric_namespace  = "TerratestNamespace"
  pattern           = "ERROR"
  alarm_name        = "TerratestAlarm"
  alarm_action_arns = [aws_sns_topic.terratest_topic.arn]
  period            = "3600"
  threshold         = "5"
  statistic         = "Sum"
}`

The metric name is automatically populated
