### ISSUE TITLE
Pipeline requiered to publish releases

### ISSUE THREAD

**Issue by dan-hill2802** [dwp/terraform-aws-metric-filter-alarm#8]
## :mag_right: Scope
* GitHub Action to publish GitHub release on commit to default branch (currently still named `master`)
* Release to be in Semver format with only numbers and dots e.g. 1.2.3
* New release number to simply be an increment of the patch number (last of the three numbers)
* (optional) Determine whether to increment the major, minor, or patch number depending on the commit message. Details of keywords can be discussed on this issue page

## :anchor: Difficulty
Here is our honest estimate on how difficult (on a scale of 1-5) the implementation may be:
:large_blue_circle: :white_circle: :white_circle: :white_circle: :white_circle:

## :memo: Relevant Classes or Snippets
Most of the [GitHub Actions pipeline in the dataworks-repo-template-docker](https://github.com/dwp/dataworks-repo-template-docker/blob/master/.github/workflows/main.yml) can be reused
* the [publish-docker](https://github.com/dwp/dataworks-repo-template-docker/blob/master/.github/workflows/main.yml#L45) job is **not required**
* the [snyk-monitor](https://github.com/dwp/dataworks-repo-template-docker/blob/master/.github/workflows/main.yml#L62) job is **not required**

## :book: Useful Resources
If you need help on how to get started, maybe try looking into the following resources!
* GitHub/Open-Source
    * [How to contribute to Open-Source](https://opensource.guide/how-to-contribute/)
    * [Working with forks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks)
    * [Creating a Pull Request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
* GitHub Actions
    * [official documentation](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions)

<hr>

If you want to work on this, simply comment down below and state your interests! Please also comment again if you have changed your mind. Anyone is allowed to discuss in the comments below, feel free to collaborate and work together :heart: <br>
You can always ask for help here if you get stuck.

**Comment by fractiunate-me** [comment]
Hello there, 

I want to tackle it. Need to get some insight into GitHub Makefile. Is there an overview of your commit-release process somewhere to get some insight into the project environment and structure?


Happy new Year, All the Best
David

**Comment by dan-hill2802** [comment]
Hi David,

Thanks for showing interest in this issue. 

We are definitely lacking written contributions guidelines. We typically follow trunk based development, using short lived branches and pull requests to the master branch. Each commit to the master branch will produce a release, in this case, a GitHub release, which in turn will create a release on Terraform Registry. For contributions from outside the core team, we typically expect a pull request from your forked repo to our master branch. Other than that, we don't have many requirements for the contribution.

Dan

**Comment by fractiunate-me** [comment]
Semver Logic is in place.

When the CI-Message contains "Major Release", it will do a Major semver upgrade, 
on  "Minor Release" a minor, 
else just a patch, you wanted to discuss the Conditions for the Semver Upgrades?

Any suggestions for the key-words or conditions?
David

**Comment by dan-hill2802** [comment]
Hi David,

Just wanted to thank you for this contribution. The team like the approach and I have now raised a change to add it to our pipeline template, so it will become our standard on all new repos.
https://github.com/dwp/dataworks-repo-template-docker/pull/13

Regards,

Dan
